AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FormatStringToken:
  Enabled: false

Style/Documentation:
  Exclude:
    - "lib/schema_reaper/runtime.rb" # nested Hook/Tracker helpers

Style/SafeNavigationChainLength:
  Enabled: false

Layout/LineLength:
  Max: 120

Naming/MethodParameterName:
  AllowedNames: [f, n, io, id, at, to, db]

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/ParameterLists:
  Exclude:
    - "spec/**/*"

Gemspec/DevelopmentDependencies:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 130

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 13

Metrics/AbcSize:
  Max: 28
